language: python
sudo: 
   - required
python:
   - "2.6"
   - "2.7"
   - "3.2"
   - "3.3"
   - "3.4"
   # - "pypy"


#Shippable Supports Python ver: 2.6, 2.7, 3.2, 3.3, 3.4 and pypy.


# before_cache:
#  - cat $HOME/.cache/pip/log/debug.log
  
before_install:
   # - "sudo pip install --upgrade pip"
   #Install SimpleITK
   # - wget www.sourceforge.net/projects/simpleitk/files/SimpleITK/0.9.1/Python/SimpleITK-0.9.1-py3.4-linux-x86_64.egg
   # - easy_install SimpleITK-0.9.1-py3.4-linux-x86_64.egg
   
   # - wget www.sourceforge.net/projects/simpleitk/files/SimpleITK/0.9.1/Python/SimpleITK-0.9.1-py2.6-linux-x86_64.egg
   # - easy_install SimpleITK-0.9.1-py2.6-linux-x86_64.egg
   
   
   # - sudo apt-get install python-dev libffi-dev libssl-dev
   # - sudo apt-get install libffi-dev libssl-dev
   # - sudo pip install pyopenssl ndg-httpsclient pyasn1
   # - sudo pip install requests[security]
   # - sudo pip install --upgrade pip
   # - sudo -H pip install SimpleITK
   
   
   
   # - sudo pip install --upgrade pip
   
   # - which easy_install
   # - sudo easy_install --install-dir /usr/local/lib/python2.7/site-packages SimpleITK
   # - sudo easy_install SimpleITK

   # - sudo easy_install --user SimpleITK
   # - sudo -H pip install SimpleITK
   
   
   
   #Works for 2.7, and 3.2 but not 2.6 or 3.3
   # - wget https://bootstrap.pypa.io/ez_setup.py -O - | sudo python
   # - wget www.sourceforge.net/projects/simpleitk/files/SimpleITK/0.9.1/Python/SimpleITK-0.9.1-py2.7-linux-x86_64.egg
   # - easy_install SimpleITK-0.9.1-py2.7-linux-x86_64.egg
   
   
   
   
   - sudo apt-get install python-pip
   - sudo pip install requests[security]
   - sudo pip install --upgrade pip
   - sudo -H pip install SimpleITK
   # - sudo pip install --allow-external SimpleITK --trusted-host www.simpleitk.org SimpleITK
   
   # --allow-unverified
   
   
   
   
   # - ls
   # - cd /usr/local/lib/python2.7/dist-packages
   # - ls
   
   
   # - "sudo pip install --upgrade pip"
   
   

# command to run tests
script: python sitkConfidenceConnectedSeg.py

cache:
   - pip
   - bundler
   - apt
   # directories:
      # - $HOME/.cache/pip


# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: never
    use_notice: true
