language: python
sudo: 
   - required
python:
   # - "2.6"
   - "2.7"
   # - "3.2"
   # - "3.3"
   # - "3.4"
   # - "3.5"
   # - "3.5-dev" # 3.5 development branch
   # - "nightly" # currently points to 3.6-dev

# before_cache:
#  - cat $HOME/.cache/pip/log/debug.log
  
before_install:
   - "sudo pip install --upgrade pip"
   #Install SimpleITK
   # - wget www.sourceforge.net/projects/simpleitk/files/SimpleITK/0.9.1/Python/SimpleITK-0.9.1-py3.4-linux-x86_64.egg
   # - easy_install SimpleITK-0.9.1-py3.4-linux-x86_64.egg
   
   # - wget www.sourceforge.net/projects/simpleitk/files/SimpleITK/0.9.1/Python/SimpleITK-0.9.1-py2.6-linux-x86_64.egg
   # - easy_install SimpleITK-0.9.1-py2.6-linux-x86_64.egg
   
   # - sudo pip install requests[security]
   # - sudo -H pip install SimpleITK
   - sudo easy_install -U SimpleITK
   

# command to run tests
script: python sitkConfidenceConnectedSeg.py

cache:
   - pip
   - bundler
   - apt
   # directories:
      # - $HOME/.cache/pip


# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: never
    use_notice: true
