language: python
sudo: 
   - required

#Shippable Supports Python ver: 2.6, 2.7, 3.2, 3.3, 3.4 and pypy
python:
   - "2.7"
   #- "3.3"
   #- "3.4"
   
# Build these specific branches
branches:
  only:
  - master
  - release

before_install:
   ####################################################
   #Works for 2.7, 3.3 and 3.4 but not 2.6, 3.2, or pypy
   - wget https://bootstrap.pypa.io/ez_setup.py -O - | sudo python
   - wget www.sourceforge.net/projects/simpleitk/files/SimpleITK/0.9.1/Python/SimpleITK-0.9.1-py2.7-linux-x86_64.egg
   - easy_install SimpleITK-0.9.1-py2.7-linux-x86_64.egg
   ####################################################
   #Install any other dependencies

   - pip install -r requirements.txt
   
script: python Testing/AutomatedTesting.py

   
# script: python Testing/ClassTesting.py

# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: never
    use_notice: true
