language: python
sudo: 
   - required
python:
   - "2.6"
  # - "2.7"
  # - "3.2"
  # - "3.3"
  # - "3.4"
  # - "3.5"
  # - "3.5-dev" # 3.5 development branch
  # - "nightly" # currently points to 3.6-dev
# command to install dependencies
#install: "pip install --upgrade pip"
before_install:
   - "sudo pip install --upgrade pip"
   - "sudo pip install --allow-external SimpleITK --trusted-host www.simpleitk.org"
  #Install SimpleITK
#  - sudo easy_install SimpleITK
#  - brew install
 
# command to run tests
script: python sitkConfidenceConnectedSeg.py

# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: never
    use_notice: true
